file=open("output.txt", "w")
user=str(input("Enter the text you want to write: "))
wrtite=file.write(user)
file.close()
print("Data written successfully to output.txt")

files=open("output.txt", "a")
user1=str(input("Enter the text you want to append: "))
write1=files.write(user1)
files.close()
print("Data appended successfully to output.txt")